#!/usr/bin/env python3
"""Generate a Windows PowerShell script that drives Microsoft Word via COM to
do paragraph-level find-and-replace on a master document, then save .doc and
export .pdf.

This is the Windows counterpart of gen_word_replace_applescript.py. Use it when
the master is a complex .doc (rotated text boxes, floating tables, imposed page
setups, custom headers) -- those only survive inside Word's own layout engine.

IMPORTANT -- Chinese encoding trap
----------------------------------
Windows PowerShell 5.1 (the default `powershell.exe`) reads a .ps1 file as ANSI
unless it has a UTF-8 BOM. A script containing Chinese text written without a
BOM comes out as mojibake and the find/replace silently fails to match.
Therefore this generator WRITES THE FILE ITSELF with `utf-8-sig` (UTF-8 + BOM)
rather than printing to stdout. Do not pipe it to a file with `>`.

Usage:
  python3 gen_word_replace_powershell.py pairs.json master.doc new.doc new.pdf -o build.ps1
  powershell -NoProfile -ExecutionPolicy Bypass -File build.ps1
  # prints: MISS:<comma-separated indexes that did not match>

pairs.json -- either a bare list, or {"pairs": [...]}:
  [["old paragraph text", "new paragraph text"], ...]

Each old/new string must be ONE paragraph (no newlines) and <= 250 characters
(Word's find limit is 255). Split multi-paragraph changes into one pair per
paragraph so intra-paragraph formatting is preserved.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

FIND_LIMIT = 250  # Word's hard limit is 255; stay under it.


def ps_quote(s: str) -> str:
    """PowerShell single-quoted literal: double any embedded single quote."""
    return "'" + s.replace("'", "''") + "'"


def load_pairs(path: Path) -> list[list[str]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    pairs = data["pairs"] if isinstance(data, dict) else data
    for pair in pairs:
        if len(pair) != 2:
            raise ValueError(f"each pair needs exactly 2 items: {pair!r}")
        for text in pair:
            if "\n" in text:
                raise ValueError(
                    f"newline in pair (split it into one pair per paragraph): "
                    f"{text[:40]!r}")
            if len(text) > FIND_LIMIT:
                raise ValueError(
                    f"text exceeds Word find limit ({FIND_LIMIT}): {text[:40]!r}")
    return pairs


def build(pairs, src: str, outdoc: str, outpdf: str) -> str:
    olds = ",\n    ".join(ps_quote(o) for o, _ in pairs)
    news = ",\n    ".join(ps_quote(n) for _, n in pairs)
    return f"""# Generated by gen_word_replace_powershell.py -- do not edit by hand.
# Requires Microsoft Word installed. The master file is never written back;
# all output goes to new files.
$ErrorActionPreference = 'Stop'

$src    = {ps_quote(src)}
$outDoc = {ps_quote(outdoc)}
$outPdf = {ps_quote(outpdf)}

$pairsOld = @(
    {olds}
)
$pairsNew = @(
    {news}
)

if ($pairsOld.Count -ne $pairsNew.Count) {{
    throw "pairsOld/pairsNew length mismatch"
}}

# Word constants
$wdReplaceAll      = 2
$wdFindContinue    = 1
$wdFormatDocument  = 0    # .doc (Word 97-2003)
$wdExportFormatPDF = 17

$word = New-Object -ComObject Word.Application
$word.Visible = $false
$word.DisplayAlerts = 0
$missList = New-Object System.Collections.ArrayList

try {{
    # Opened read-write, but the master is never written: we only ever call
    # SaveAs2/ExportAsFixedFormat to NEW paths, never $doc.Save(). This keeps
    # the master intact while avoiding SaveAs-from-read-only quirks.
    $doc = $word.Documents.Open($src, $false, $false)

    for ($i = 0; $i -lt $pairsOld.Count; $i++) {{
        $rng = $doc.Content
        $f = $rng.Find
        $f.ClearFormatting()
        $f.Replacement.ClearFormatting()

        # Execute(FindText, MatchCase, MatchWholeWord, MatchWildcards,
        #         MatchSoundsLike, MatchAllWordForms, Forward, Wrap,
        #         Format, ReplaceWith, Replace)
        $ok = $f.Execute($pairsOld[$i], $true, $false, $false, $false,
                         $false, $true, $wdFindContinue, $false,
                         $pairsNew[$i], $wdReplaceAll)
        if (-not $ok) {{ [void]$missList.Add($i) }}
    }}

    # SaveAs2 renames the open document; the master on disk is untouched.
    $doc.SaveAs2($outDoc, $wdFormatDocument)
    $doc.ExportAsFixedFormat($outPdf, $wdExportFormatPDF)
}}
finally {{
    if ($doc) {{ $doc.Close(0) }}
    $word.Quit()
    [System.Runtime.InteropServices.Marshal]::ReleaseComObject($word) | Out-Null
}}

Write-Output ("MISS:" + ($missList -join ','))
"""


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("pairs", type=Path)
    ap.add_argument("src")
    ap.add_argument("outdoc")
    ap.add_argument("outpdf")
    ap.add_argument("-o", "--out", type=Path, required=True,
                    help="output .ps1 path (written as UTF-8 with BOM)")
    args = ap.parse_args()

    if not args.pairs.exists():
        print(f"ERROR: no such file: {args.pairs}", file=sys.stderr)
        return 2
    try:
        pairs = load_pairs(args.pairs)
    except (ValueError, KeyError) as e:
        print(f"ERROR: bad pairs file: {e}", file=sys.stderr)
        return 2

    # utf-8-sig == UTF-8 with BOM: required for Windows PowerShell 5.1 to read
    # Chinese text correctly. Writing without the BOM causes mojibake.
    args.out.write_text(build(pairs, args.src, args.outdoc, args.outpdf),
                        encoding="utf-8-sig")
    print(f"wrote {args.out} (UTF-8 with BOM, {len(pairs)} replacement pairs)")
    print(f"run:  powershell -NoProfile -ExecutionPolicy Bypass -File {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
